version: '3.4'
services: 
  ml_server:
    container_name: ml_server
    image: ${DOCKER_REGISTRY-}ml_server
    build:
     context: .
     dockerfile: ml_serv/Dockerfile
    networks:
      my-network:
        aliases:
          - ml_server
    ports:
     - "8080:5000"
     
  nginx:
    image: nginx:1.13.7
    depends_on:
     - ml_server
    ports:
     - 80:80
    networks:
      - my-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    
networks:
    my-network:
  